spring:
  application:
    name: eureka-zuul
  zipkin:
    base-url: http://192.168.153.161:9411
  sleuth:
    sampler:
      probability: 1.0 # 100%的概率将链路的数据上传给Zipkin Server
server:
  port: 5000
eureka:
  client:
    service-url:
      defaultZone: http://192.168.153.156:8761/eureka/

zuul:
  routes:
    hiApi:
      path: /hiApi/**
      serviceId: eureka-client
    ribbonApi:
      path: /ribbonApi/**
      serviceId: eureka-ribbon-client
    feignApi:
      path: /feignApi/**
      serviceId: eureka-feign-client

  prefix: /v1
