spring:
  application:
    name: eureka-ribbon-client

server:
  port: 8765

# 暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://192.168.153.156:8761/eureka/
