spring:
  application:
    name: config-server
server:
  port: 8770

eureka:
  client:
    service-url:
      defaultZone: http://192.168.153.156:8761/eureka/
---
# 在本地加载配置文件
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared

---
# 从远程仓库加载配置文件
spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SJshenjian/spring-cloud # 仓库名
          search-paths: config # 包名
          username: SJshenjian
          password:
          default-label: master
